# Generated by Django 3.2.8 on 2021-10-17 23:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='expT',
            field=models.CharField(default=1634514277, max_length=50),
        ),
        migrations.AlterField(
            model_name='resetpassword',
            name='expT',
            field=models.CharField(default=1634514277, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.CharField(default=datetime.datetime(2021, 10, 17, 23, 29, 37, 675535), max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pass_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
