# Generated by Django 3.2.7 on 2021-10-10 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_test'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='test',
            managers=[
                ('test', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
