# Generated by Django 3.2.8 on 2021-10-18 21:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211018_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='expT',
            field=models.CharField(default=1634592544, max_length=50),
        ),
        migrations.AlterField(
            model_name='resetpassword',
            name='expT',
            field=models.CharField(default=1634592544, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.CharField(default=datetime.datetime(2021, 10, 18, 21, 14, 4, 845803), max_length=50, null=True),
        ),
    ]
