# Generated by Django 3.2.7 on 2021-10-10 22:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211010_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='add_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='add', to=settings.AUTH_USER_MODEL),
        ),
    ]
