# Generated by Django 3.2.8 on 2021-10-26 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211024_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='paid_status',
            field=models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('not_paid', 'not_paid')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='expT',
            field=models.CharField(default=1635284168, max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resetpassword',
            name='expT',
            field=models.CharField(default=1635284168, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.CharField(default=datetime.datetime(2021, 10, 26, 21, 21, 8, 764141), max_length=50, null=True),
        ),
    ]
