# Generated by Django 3.2.8 on 2021-10-27 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211026_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='expT',
            field=models.CharField(default=1635356792, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=3.0),
        ),
        migrations.AlterField(
            model_name='resetpassword',
            name='expT',
            field=models.CharField(default=1635356792, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.CharField(default=datetime.datetime(2021, 10, 27, 17, 31, 32, 711586), max_length=50, null=True),
        ),
    ]
