# Generated by Django 3.2.8 on 2021-10-28 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20211028_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='expT',
            field=models.CharField(default=1635463389, max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='category',
            field=models.CharField(default='dd', max_length=50),
        ),
        migrations.AlterField(
            model_name='resetpassword',
            name='expT',
            field=models.CharField(default=1635463389, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.CharField(default=datetime.datetime(2021, 10, 28, 23, 8, 9, 917817), max_length=50, null=True),
        ),
    ]
