# Generated by Django 3.2.9 on 2021-11-07 22:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20211107_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='seen',
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='expT',
            field=models.CharField(default=1636326363, max_length=50),
        ),
        migrations.AlterField(
            model_name='resetpassword',
            name='expT',
            field=models.CharField(default=1636326363, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.CharField(default=datetime.datetime(2021, 11, 7, 22, 51, 3, 374789), max_length=50, null=True),
        ),
    ]
