# Generated by Django 3.2.9 on 2021-11-23 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20211107_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_for',
            field=models.EmailField(default='dsfefewfew@gmailcom', max_length=200),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='expT',
            field=models.CharField(default=1637658470, max_length=50),
        ),
        migrations.AlterField(
            model_name='resetpassword',
            name='expT',
            field=models.CharField(default=1637658470, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.CharField(default=datetime.datetime(2021, 11, 23, 8, 52, 50, 384494), max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='SpecialOrder',
        ),
    ]
