# Generated by Django 3.2.9 on 2021-11-23 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20211123_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='expT',
            field=models.CharField(default=1637658580, max_length=50),
        ),
        migrations.AlterField(
            model_name='resetpassword',
            name='expT',
            field=models.CharField(default=1637658580, max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_for',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.CharField(default=datetime.datetime(2021, 11, 23, 8, 54, 40, 303980), max_length=50, null=True),
        ),
    ]
